echo Compiling modules...
c++ -std=c++11 -c tools.cpp -o tools.o

echo Organizing modules into libraries...
ar rcs libtools.a tools.o

echo Building main and linking the library...
c++ -std=c++11 main.cpp -L . -ltools -o main
